/**
 * OpenAPI Sample API v2
 * Sample API for an OpenAPI conference talk.</br>This document was automatically generated as of 25.09.2019 06:32:09.
 *
 * OpenAPI spec version: v2
 * Contact: sebastian.gingter@thinktecture.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ProblemDetails { 
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
    readonly extensions?: { [key: string]: any; };
}